### ISSUE TITLE
"vertex" -> "node"

### ISSUE THREAD

**Issue by jrtom** [jrtom/jung#107]
The new term of art is "node", so replace "vertex" with "node" (and "V" where it refers to a node type with "N").

**Comment by tomnelson** [comment]
I've completed this in my develop branch for jung-visualization and jung-samples. It touched a lot of files.

**Comment by tomnelson** [comment]
I also updated the `fooTransformer implements Function` to `fooFunction implements Function` everywhere

**Comment by jrtom** [comment]
Thanks!  :)

I expect that there's still a lot of cleanup to be done elsewhere, and a number of places that we have "V" that we want to be "N", but progress is good.

**Comment by tomnelson** [comment]
I believe that my latest code offering completes the transition from V to N and from vertex to node.

**Comment by jrtom** [comment]
Closing.  We may still have a few edge cases around, and we've got a number of places where we use 'v' as a variable name where 'n' is now more appropriate, but I think that's minor enough that we can retire this issue.

@tomnelson a belated thanks for taking care of this.  :)
