### ISSUE TITLE
Switching layouts is busted [common.graph]

### ISSUE THREAD

**Issue by jrtom** [jrtom/jung#109]
This issue has two parts: fixing VisualizationViewer so that switching layouts actually works, and fixing the sample code so that the selection and creation of Layouts works (i.e., no longer uses reflection).

The first part manifests in several demos, including `BalloonLayoutDemo`, `*AddNodeDemo`, `L2RLayoutDemo`, `TreeLayoutDemo`, `VertexCollapseDemoWithLayouts`.

**Comment by tomnelson** [comment]
This was the result of the stateful Network in many, many places. It should be fixed in the visualization-fixes branch.

**Comment by jrtom** [comment]
This should have been resolved by (and verified in) #145 (thanks to @tomnelson).  If this comes up again, we can reopen this issue.
