### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by jbduncan** [jrtom/jung#115]
When I submitted #114 for review, I noticed that the checks finished rather quickly. I investigated and it seems that Travis CI is actually not running at all - only _CLA assistant_ runs AFAICT - so we don't know if changes coming in even meet the minimum requirements!

I think this requires someone with admin privileges over the `jung` repository to set up the service (probably only @jrtom has the required privileges to do so currently).

**Comment by jrtom** [comment]
@cgruber also has such privileges (and he set it up in the first place) but if you have information on what changes need to take place, please LMK and I'll try to get it sorted.  Thanks.

**Comment by jbduncan** [comment]
@jrtom I think the first thing to check is to see if you've enabled Travis CI for your GitHub account and for this repository. It looks like there's information over at https://docs.travis-ci.com/user/getting-started/ on how to do this.

I hope this is the sort of information you were after.

**Comment by jrtom** [comment]
It looks like CI is set up for JUNG: https://travis-ci.org/jrtom/jung
but not for the common.graph branch in particular: 
https://travis-ci.org/jrtom/jung/branches

I've edited .travis.yml (on both the master and common.graph branches) to add common.graph to the list of branches to build, so let's see if that helps.

**Comment by jrtom** [comment]
The good news: that seems to have worked.

The bad news: common.graph is reporting errors on Travis: 
https://travis-ci.org/jrtom/jung/builds/270224350

:/

I'll see if I can figure that out, but feel free to have a look if you don't see an update on this thread by the time you read it.

**Comment by jbduncan** [comment]
It's not immediately obvious to me why the logs seem to say that certain type-variables cannot be inferred, but I do notice that Travis is using a rather old version of Java 8 - 1.8.0_31, specifically - where the latest version as of now is 1.8.0_144.

So we might be able to resolve this type-inference problem by using a more recent JDK (which would have more type-inference bug fixes), which I believe we can do either by [changing our JDK to OpenJDK 8](https://github.com/travis-ci/travis-ci/issues/6483#issuecomment-294273796) or by using the [Oracle JDK 8 from the Ubuntu apt repositories](https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338).

**Comment by jrtom** [comment]
Supposedly dist:trusty should be the default as of August 2017--now almost over--but I can see from the build output that it's still using precise.  Sigh.

Fixed to use trusty, and added OpenJDK8 to both common.graph and master branches.  common.graph now builds.

Calling this done; please reopen if you think there's still work to be done.

**Comment by jbduncan** [comment]
LGTM overall. I'm a little sad that Travis's default version for OpenJDK 8 is 1.8.0_111, rather than something more recent, but compared to before, it's much better and, as you said, the common.graph branch passes now, so I'm happy enough to leave things as-is.
