### ISSUE TITLE
Create spatial data structures for visualization

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#124]
I created a branch (off of an older version of jung) that adds a spatial data structure for rendering. It is also tested in layouts, with a less satisfying result. The branch name is 'spatial'

**Comment by jrtom** [comment]
Cool, I look forward to hearing more about this.  Thanks for looking into it!

How does it change the performance of the visualization (especially any qualitative changes you perceived)?  How is it less satisfying in layouts?  (Obviously it's only relevant to ones in which you care about proximity, i.e., the force-directed layouts.)

**Comment by tomnelson** [comment]
Check out the branch and run some demos!

ShowLayouts has 2 new layouts that (naively) use the SpatialGrid. You may have some ideas about how to use it more effectively in Layouts

All of the visualization demos now use the SpatialGrid. I upped the size of the PluggableRendererDemo graph. Run it, pan around some, then zoom way in and pan around some more. Maybe it is wishful thinking, but I think it is smoother.

This is very experimental so there are certainly optimizations available for what I wrote. I just wanted to see how it could be applied.

**Comment by tomnelson** [comment]
The current visualization pipeline goes something like this:
- get all the graph elements (nodes, edges)
- apply the layout to get a location O(1)
- gather the shapes for nodes, edges, labels, etc
- project the visible screen onto the layout
- intersect each shape with the visible screen projection
  - if they intersect, draw the shapes

With a Spatial data structure, it could work like this:
- divide the layout into a grid, each grid cell number maps to a list of nodes
- project the visible screen onto the layout
- get the grid cells that intersect with the projection
- iterate over only the nodes that are in visible grid cells
- for each edge, supply only those that have at least one endpoint that is 'visible'
This allows skipping the 'expensive' operation to intersect the shapes with the screen projection

**Comment by tomnelson** [comment]
Here is a short video about the JUNG Spatial Grid:
https://drive.google.com/file/d/0B84Z0p-oCQFsczliRUk2U1daVWs/view?usp=sharing

In this case, a 10x10 grid is formed over the layout area. Each grid cell has an index and there is a map of index to contained nodes. Since we allow users to drag a node outside of the original layout area, the grid must be updated when this happens (shown). The index must be recreated when nodes are moved.

During visualization, the visible area is projected onto the layout grid and a collection of nodes is returned for the grid cells that are visible. This reduces the work for rendering of the graph components by skipping any that are in hidden cells.

When logging is set to the TRACE level, the grid is drawn under the graph using the Annotations feature.

**Comment by tomnelson** [comment]
resolved in PR #149
