### ISSUE TITLE
Tree types need to implement hashCode() and equals()

### ISSUE THREAD

**Issue by jrtom** [jrtom/jung#132]
Because otherwise it turns out that they don't work.  Surprise!

**Comment by jrtom** [comment]
So I looked into this and I'm a bit puzzled.

`DelegateCTree` and `DelegateCTreeNetwork` each extend the appropriate abstract class (`AbstractGraph` and `AbstractNetwork`, respectively).  Each of which defines `equals()` and `hashCode()`.

Looking again at the discussion in #131, I think I need to take a close look at the test failure, because `AbstractNetwork.equals()` should just do the right thing here; there's no reason IMO to say that a `Network` which happens to be isomorphic to a `CTreeNetwork` isn't equal to it.

**Comment by jbduncan** [comment]
Yes, that is a bit puzzling...

I may have time within the next few days to have a look at #131 as well. If I do, I'll report back here or there. :)

**Comment by jrtom** [comment]
...I have no idea why that test was failing originally, but if I change the test so that it's comparing the `Network`s directly it still passes.  Changing the test in #226 so that it just compares the graphs directly.

**Comment by jbduncan** [comment]
That sounds good to me. Let's address this if and only if it crops up again.
