### ISSUE TITLE
DijkstraShortestPath::getPath() does not clear sourceMap when cached is false

### ISSUE THREAD

**Issue by peterguy** [jrtom/jung#134]
`getIncomingEdge` and `getIncomingEdgeMap` both clear the cache by calling `DijkstraDistance::reset(V source)`, but `getPath()` does not.

Is that by design, or by oversight?

Also, is this the correct forum for a question like this? It seems rather specific for SO, but it doesn't seem like an "issue" yet, either.

Thanks!

**Comment by jrtom** [comment]
@peterguy Definitely an oversight; thanks for the catch.  :)

Yes, this is definitely the right forum for reporting behaviors that look to you like bugs, or for requesting features.  StackOverflow is good for asking how-to questions.  Thanks for asking.

This is being fixed in #227.
