### ISSUE TITLE
restore 3d graph visualization

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#136]
I updated my old 3d version of jung visualization to use common.graph. Here's a link to a video of the demo: https://drive.google.com/open?id=0B84Z0p-oCQFsWmxwZGdHY1VoZTg

It's nice that the dependencies are all available in maven now so you can easily run it without installing any native libraries on your computer.

**Comment by tomnelson** [comment]
I'll put this in a separate github repo

**Comment by jrtom** [comment]
Sorry I didn't get back to this sooner.  I agree that this is probably a better fit for a separate repo.  Thanks!
