### ISSUE TITLE
PajekNetReader was broken when it was updated to use Preconditions

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#137]
commit id 235c036f40e964c691e401df9bb60fd31b5d0599
'Now uses Preconditions checks where possible'

changed this:

` if (initial_split.length < 2 || initial_split.length > 3)
                throw new IllegalArgumentException("Unbalanced (or too many) " +
                		"quote marks in " + curLine);`

to this:

    ` Preconditions.checkArgument(
          initial_split.length == 2, "Unbalanced (or too many) " + "quote marks in " + curLine);`

and they are not the same condition because the split length in our test file is 3.

This breaks the ClusteringDemo.

**Comment by jrtom** [comment]
Yup, that's a bug all right.  Fix incoming.
