### ISSUE TITLE
Add QuadTree spatial data structure for O(logN) performance (vice O(N) for location based searches.

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#146]
Here's a look at what the QuadTree structure looks like and how it dynamically updates:
https://youtu.be/rmPx_ievyLc

**Comment by jrtom** [comment]
Interesting.  One thing that puzzles me: under what circumstances does a region get split up into 4 subregions?  During the last part of the animation, you were moving a node from one region to an adjacent one, and one region split itself into 4, but the other region didn't.  Each region had either 0 or 1 nodes in it at the time.

**Comment by tomnelson** [comment]
The number of nodes per region is settable. It is set to 1 in this demo.
Whenever there are > 1 nodes in a box, the box is split into 4 (the parent
gets 4 child nodes) and the nodes go into the correct leaf of the tree.
The nodes is 'in' a region if its center point is in the region. The actual
shape of the node can overlap an adjacent region that it is not 'in'.

**Comment by tomnelson** [comment]
resolved by PR #149 and #146
