### ISSUE TITLE
Consider removing `DiscreteDistribution.[kullbackLeibler|symmetricKL]

### ISSUE THREAD

**Issue by jbduncan** [jrtom/jung#148]
Following on from https://github.com/jrtom/jung/pull/143, I'd like to suggest that we remove `DiscreteDistributon.kullbackLeibler()` and `DiscreteDistribution.symmetricKL()`. These methods aren't currently being used anywhere in JUNG, and it's not clear to me that they're useful outside of JUNG.

Pros for removing these methods:
1. Codebase would be less cluttered.
2. One thing less to test.

Cons:
1. These methods may be being used by JUNG 2.x users (since they are public API, as pointed out by @jrtom [here](https://github.com/jrtom/jung/pull/143#issuecomment-344032673)), in which case we should likely move the methods out of the `utils` package (which may become an `internals` package, as discussed in https://github.com/jrtom/jung/issues/94) and into a more dedicated class elsewhere.

It also occurs to me that the name of the methods aren't so user friendly. One could Google what Kullback-Leibler divergence is, but I personally find the [Wikipedia article](https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence) too technical. So if we decide to keep these methods, it would be good to rename them to say _what_ they do, instead of how, and then say in the JavaDoc that the implementation in based on Kullback-Leibler.

**Comment by jrtom** [comment]
Kullback-Leibler divergence is something that I would definitely expect people to have heard of if they're trying to measure the distance between two probability distributions; that's what it's for.

It is sufficiently specific a metric that I don't think that it would be appropriate to rename it.

That said: one can pretty easily make the case that this class shouldn't have been part of JUNG in the first place, since it doesn't have anything to do with graphs per se.  (It's a tool that I was using for my research a long time ago, but I don't specifically need it now, and if I do need it it's not hard to recreate.)

There are two methods in it still in use by JUNG: mean() and squaredError().  They're both used only in VoltageClusterer (and as you noted, we can use Guava's Stats.meanOf() to handle the former).  So I would recommend just moving squaredError() into VC, and then reworking VC to use Stats.meanOf().

**Comment by jbduncan** [comment]
> Kullback-Leibler divergence is something that I would definitely expect people to have heard of if they're trying to measure the distance between two probability distributions; that's what it's for.

Okey dokey, that sounds like a very good reason to me to keep the names then. :)

> That said: one can pretty easily make the case that this class shouldn't have been part of JUNG in the first place, since it doesn't have anything to do with graphs per se. (It's a tool that I was using for my research a long time ago, but I don't specifically need it now, and if I do need it it's not hard to recreate.)

Hmm... I'm not really sure what to make of this, or where to go from here.

May I take this as an invitation to remove `DiscreteDistribution::[kullbackLeibler|symmetricKL]` in a separate PR? Or would you prefer another course of action - even if it's just waiting for someone else to chime in?

> ...So I would recommend just moving squaredError() into VC, and then reworking VC to use Stats.meanOf().

Cool, I'll handle that in a separate PR. :+1:

**Comment by jrtom** [comment]
What I am proposing is that we actually nuke the entire `DiscreteDistribution` class, and move the one method that we still need to preserve (`squaredError`) into the class that uses it (`VoltageClusterer`). 

So you can reopen #143 and broaden its scope, if you like, or create a new PR.

**Comment by jbduncan** [comment]
Thank you @jrtom for the guidance!

I've re-opened #143 and nuked `DiscreteDistribution`. However, since `DiscreteDistribution.mean` was being used in both `KMeansClusterer` and `VoltageClusterer`, I decided to move it to a new `edu.uci.ics.jung.algorithms.internals.MathUtils` class. And since it makes sense to me that I should test methods like `mean` later in #142 or a new PR, I decided to move `squaredError` to the new class as well.

It's not clear to me if this is what you wanted, so please let me know what you think.

**Comment by jrtom** [comment]
Can we just use the Guava Stats.meanOf() instead of rolling our own?

**Comment by jbduncan** [comment]
Guava's `Stats.meanOf()` can take the mean of a `double[]`, but it cannot take the mean of each `double[]` in a `Collection<double[]>` and return those means as a new `double[]`, as we currently do. So, AFAICT, we need something like this:

```java
private static double[] meansOf(Collection<double[]> collectionOfDoubleArrays) {
  double[] result = new double[collectionOfDoubleArrays.size()];
  int index = 0;
  for (double[] doubleArray : collectionOfDoubleArrays) {
    result[index++] = Stats.meanOf(collectionOfDoubleArray);
  }
  return result;

  // or

  return collectionOfDoubleArrays.stream().mapToDouble(Stats::meanOf).toArray();
}
```

**Comment by jrtom** [comment]
Yeah, sorry I wasn't more precise about that.

Personally I think that that's a reasonable place for a `Stream` if you want to implement it that way (and that way you could just ditch the method entirely).

Let's do further comments on the PR itself, so we don't keep splitting the discussion.  :)

**Comment by tomnelson** [comment]
I think stream is pretty there, but this is code that should probably be as
fast as possible.

**Comment by jbduncan** [comment]
> Let's do further comments on the PR itself, so we don't keep splitting the discussion. :)

Okay! Let's. :)

**Comment by jbduncan** [comment]
@tomnelson Okay, it's not the first time that you've seemingly rejected the idea of using `Stream`s at all. Is this on purpose?

**Comment by tomnelson** [comment]
Do you think it is acceptable to use streams in algorithmic code?

https://blog.takipi.com/benchmark-how-java-8-lambdas-and-streams-can-make-your-code-5-times-slower/

**Comment by jbduncan** [comment]
1. Define what you mean by "algorithmic", because I'm not 100% clear what that means.
2. I believe that such a difference in speed between standard for-loops and streams is simply not noticeable in practice _unless_ the data one is working with is "significantly" large enough _or_ the code is a hot path. I also believe that the only way to determine whether a dataset is "significantly" large or whether a piece of code is a hot path is to do benchmarking or profiling respectively. Blogs can give an idea of how fast something will run, but IMO we can't know for sure how it would work in _our_ case unless we test it. Anything else is arguably premature optimisation.

**Comment by tomnelson** [comment]
I would look at the source for something like Stats.meanOf and see if they
use streams.
I suspect they know more than we do about performance.

**Comment by jrtom** [comment]
The results at the top of that blog article (and the link name) are misleading; scroll down to the bottom for the revised results.  According to the revised results, all of those microbenchmarks except one (not the Stream-based one) perform pretty close to the same.

That said, I agree with @jbduncan that I'm willing to be convinced by benchmarks on actual code, but I don't find microbenchmarks like these to be particularly convincing.

Guava doesn't use Java 8 constructs internally except where it relates to Java 8 APIs (so as to minimize diffs between the Java 7 and 8 versions of Guava) so that doesn't tell us anything.

Guava is also generally not super-invested in performance tuning of its libraries, in part because (as implied above) microbenchmarks are often misleading.

As noted above
(a) please let's take further discussion to #143 
(b) I remain OK with using a Stream in this case.  It's an internal implementation detail and we can change it later if we decide that it's worth it.
(I'm also OK with _not_ using a Stream here, but this seems like a good place for one, readability-wise.)

**Comment by jbduncan** [comment]
> I would look at the source for something like Stats.meanOf and see if they
use streams.

As it turns out, I have. I agree that it uses an imperative implementation, but the Guava folks likely went down the imperative route because they expect `Stats.meanOf` to be used with humungous datasets on top of smaller ones. Do we need to work with such large datasets where-ever we use `meansOf`? Somehow I doubt it.

> I suspect they know more than we do about performance.

I agree. But let's leave the discussion of performance to those who know what they're talking about. I know I don't - the JVM's an immensely complicated beast, after all. :)

**Comment by tomnelson** [comment]
Perhaps you should open a PR against guava where you change Stats.meanOf to use streams. The follow-on discussions might be very interesting. There would be a lot of visibility to it, so you would really get your name out there in the community. I'm not sure it would work in your favor though.

**Comment by jbduncan** [comment]
> Perhaps you should open a PR against guava where you change Stats.meanOf to use streams. The follow-on discussions might be very interesting.

I'm pretty sure that such a PR would be shot down until both `guava` and `guava-android` require Java 8 as a minimum. And even then, my impression of the Guava team is they'd only accept it if a Caliper or JMH benchmark was written that shows a valuable speed improvement. I'd rather spend my free time at the moment improving JUNG and other open source projects.

> There would be a lot of visibility to it, so you would really get your name out there in the community. I'm not sure it would work in your favor though.

Okay, I hear you, so how about we agree to disagree on this?

**Comment by jrtom** [comment]
@jbduncan is correct on both counts, as I said earlier.

@tomnelson you may not be aware that @jbduncan is already quite an active (and well-regarded) participant in the Guava community.  :)

Closing this issue, as #143 is now merged.

It sounds like we would benefit from a general agreement on the usage of Streams in JUNG, but let's open a separate issue to thrash that out.
