### ISSUE TITLE
Port to Android

### ISSUE THREAD

**Issue by DavePosner** [jrtom/jung#151]
Has anyone looked into porting the Jung visualization component to Android?  Any feeling for how hard that would be to do?

**Comment by jbduncan** [comment]
I've personally not looked into this, but I imagine it would be quite difficult, because `jung-visualization` uses Swing, whereas I remember Android's UI toolkit being very different when I last used it (albeit that was three or so years ago).

@jrtom @tomnelson, do you have any further thoughts?

**Comment by jrtom** [comment]
I have ~no practical experience with the Android UI toolkit, but my understanding is that they are very different indeed and one would need to basically start from scratch in a lot of respects.

@tomnelson has been doing some good work recently on making aspects of the visualization system less tied to AWT/Swing, but I don't think that we have any plans to try to do this port ourselves, or have that be part of JUNG.  If you have more questions, feel free to reopen this issue, and if you get inspired and come up with something that works well for you, we'd be happy to link to it.  :)
