### ISSUE TITLE
Can I use a JButton inside a vertex?

### ISSUE THREAD

**Issue by renanlf** [jrtom/jung#152]
Hi,

I need to put a **JButton** inside of my vertices and tried like that [StackOverflow](https://stackoverflow.com/questions/14731898/jung-graph-with-gui-jframe-as-node) issue and using VertexRenderer way don't worked for me too. I guess that occurs because we used the draw method.

Do have a way to can click in a JButton inside a JPanel Vertex, or something like that?

**Comment by tomnelson** [comment]
The way I would approach this is to look at the JUNG VertexLabelAsShapeDemo, which uses a DefaultVertexLabelRenderer (which extends JLabel) and positions it properly. Then I would search online for solutions to placing a JButton in the cell of a JTable. I think the approach would be very similar. You may want to create a DefaultVertexButtonRenderer extending JButton.

**Comment by renanlf** [comment]
I tried to create a new VertexLabelRenderer extending the JButton class, like the DefaultVertexLabelRenderer, but the action listener event don't fire.

**Comment by tomnelson** [comment]
There's a lot more to it than that. The JLabel (or JButton) renderer is
just used like a rubber stamp to make a picture of the JLabel (of JButton).
It does not add a real JLabel instance for every node. It's very much like
the way it works adding a special renderer to a JTable cell: It's just a
picture of a JLabel in a JTable cell, not an actual JLabel. I think you can
search online for some solutions to the JButton in a JTable problem that
will be similar to what you would want to do.

**Comment by renanlf** [comment]
I did what I needed in a different way. I changed the PickingGraphMousePlugin mouse released method to verify if the position clicked is the position of my button. If it's true so I do the stuff I want to.

But I understood better what you said about the JTable and I will search for something in that way too.

Thank you very much for the help! :)

**Comment by tomnelson** [comment]
Another idea that might be very nice.... Create a subclass of one of our Layout classes and have it implement java.awt.LayoutManager. Then, you could create a graph where the node type is JButton and set the java.awt.Container layout manager to the JUNG layout that you overrode.
Add real JButton nodes to your graph and let the java.awt.Container place the JButtons according to the JUNG layout. The layoutContainer method will use the JUNG Layout to setBounds on each JButton node. The event dispatching should work just like it would with any other swing Container of JButtons.
