### ISSUE TITLE
Picking improvements

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#153]
The current implementations of picking (and also the transformation stack) is overly complex. Depending on the use of view modifications (like the Lens views) picking is accomplished by comparing a view coordinate system mouse point or rectangle with all of the graph elements transformed from the layout coordinate system to the view coordinate system. This is overly complex and also complicates the use of spatial data structures.
Refactoring will be to always do picking tests in the layout coordinate system (where the spatial structure is) by transforming the mouse pick point or target shape from view to layout coordinate system and testing points and shapes in the layout coordinate system. I predict that this will eliminate quite a bit of complex code, and the refactoring will present an opportunity to carefully document and comment the implementation code.

**Comment by jrtom** [comment]
This sounds like a good idea.  Aside from the opportunities for simplifying the code (which I look forward to) I think that there's value to be had in making a more definite statement that the layout coordinates are the "source of truth" and that the view coordinates are a transformation of those coordinates.  Causing picking to operate on the layout coordinates seems like that would be a good step in that direction.

I will observe that layout to view transformations are not (as far as I know) constrained to be invertible, or even uniform, so it's possible to have a case in which a pick would be closer to one node in the view coordinates but closer to a different node in the layout coordinates, but I'm fine with stating that picking only works well with well-behaved transformations (although characterizing that precisely might be a bit tricky).

**Comment by tomnelson** [comment]
resolved by PR #149
