### ISSUE TITLE
Question: graph layout for directed cyclic graphs

### ISSUE THREAD

**Issue by lwhite1** [jrtom/jung#154]
Hi, and thanks for maintaining this beautiful library.

I'm attempting to map process flows. My graphs are directed graphs with cycles. All have a single start node and a single end node, with linear flows containing branching and cycles between.  

For clear presentation, I need the layout to reflect the logical flows - that is, I need the arrows to point in the same direction, with backward-facing arrows only when there is a cycle back to a prior step. This link shows a (cheesy) [example of the basic idea]( http://www.conceptdraw.com/How-To-Guide/picture/Flowchart-Project-Management-Life-Cycle.png).

[Edit] I suspect it would be easy enough to specify the Y coordinates for each node (assuming the graph flows top-down) but the horizontal spacing would have to depend on the width of the plot at it's widest point. and somehow place nodes at a particular level near the nodes above and below that it is connected to. [End Edit], 

My questions:

- Do you know of any existing layouts for this?
- If I were to attempt to create one, are there any layout algorithms in Jung that would serve as an ideal starting place? 
- Does creating such a layout seem very difficult? :)

Thanks again for all your hard work. 
Larry

**Comment by tomnelson** [comment]
Do you already know how many 'nodes' you want and what the overall , or are
you making something more dynamic?
If you already know how many nodes, you can just use StaticLayout and set
the locations you like.
If it is more dynamic, you could start with TreeLayout and modify the logic
to make the deepest path vertical down the middle with child nodes laid out
horizontally. Post a picture somewhere when you are done!

**Comment by jrtom** [comment]
Larry:

If you're just trying to lay out a single graph (say, for a slide in a presentation), then JUNG (or any general graph library, really) is probably overkill.  If I were trying to do something like that, I'd probably just use OmniGraffle or Visio or something.

The layout algorithms that JUNG implements are more for general graphs (or, in some cases, trees) in which the relationships are often highly complex, and generally nonuniform.

What's your overall goal?

**Comment by lwhite1** [comment]
I'm dynamically mapping paths through a production process starting from
raw data collected from instruments. Different orders take different routes
and i want to be generate a map for any order and also generate a map that
shows the aggregate flows from many orders.

I've started messing around with TreeLayout and have something that is
starting to work.

Thanks for your help.

**Comment by jrtom** [comment]
@lwhite1 As far as I can tell this issue is as resolved as it needs to be on our side.  If I'm mistaken, please reopen.  (Although this kind of question would have been a better fit for a StackOverflow issue with the "jung" tag.)
