### ISSUE TITLE
Spatial Data Structures

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#165]
I thought I would document my recent work as an 'issue' in order to serve as a place to discuss and document design approaches.

I've been doing quite a bit of work with Spatial Data Structures in JUNG. My early experiments were with a simple Grid structure, and then with a QuadTree. In both cases, they were applied at the LayoutModel level as special subclasses. These structures dealt only with point data (where the LayoutModel places the nodes). The LayoutModel knows nothing about the actual shapes for nodes, and knows only that an edge connects two of its node points. 

Next, I made an R-Tree. The R-Tree deals with the actual rectangular bounds of graph elements: shaped nodes and shaped edges. As such, it cannot be placed in the Model side (LayoutModel and VisualizationModel) side of JUNG, because the classes that assign the shapes to nodes and edges exist in the VisualizationServer (parent interface of VisualizationViewer)... the View side.

I implemented the R-Tree Spatial data structure on the View side as a filter for actions like find the picked node/edge, find the closest node/edge. It made the most sense to have one R-Tree for Edge shapes and one for Node shapes.

The R-Tree code is a challenge to write, because there is high complexity and several interesting edge cases. That is where most of my time has been spent.

While working with this, it occurred to me that when a graph layout is very active (like the prerelax stage of a layout algorithm or even during the relax phase of something like our SpringLayoutAlgorithm, it is not efficient to repeatedly update the spatial data structure while all that motion is happening during the 'steps' of the relax phase. Even in the case where a node is being mouse-dragged to a new location, it makes more sense to update the spatial data structure only after the user stops dragging the node and not at every step of the way. That eliminates a lot of unnecessary and competing compute cycles.

I designed the SpatialRTree so that it can either be 'active' or 'not-active'. When it is switched to 'active', it builds the spatial structure tree. During the time it is 'inactive', requests from user's mouse interaction for tool-tips or picking fall back on an O(N) approach. This seems like a good trade-off. While the R-Tree is active, requests (using the mouse pointer) for nodes during picking and when finding 'tool-tip' popup texts are quite fast, as the correct node or edge is found in O(logN) time instead of O(N). This matters a lot more as N becomes large.

**Comment by jrtom** [comment]
Thanks for writing this up; this is helpful to get a higher-level view as to what you've been up to in this part of the code, and how some of the pieces fit together.

Some comments/questions:

(0) It would be helpful if you could say a few words about how layout algorithms, layout models, and the visualization model fit together.  (Doesn't really belong in this issue, but it would help to provide some additional context for it.)

(1) It's historically been the case that our layout algorithms haven't known anything about the node shapes (or edge shapes, for that matter).  This makes it easier to write a layout algorithm, and means that layout algorithms don't have to know anything about data structures for representing node shapes, but I could imagine a subtype of layout algorithm that would be able to make use of the node shape information.  (Even outside the context of spatial data structures such as R-trees, we've gotten occasional requests for this sort of thing, presumably to make it easier to avoid node overlap.)  What are your thoughts on this?

(2) How does the quality of the layout differ if you update the spatial data structure during the relax phase versus not doing so?  I would think that it would be important that you update that for the force-directed layouts in particular, so maybe there's something about how you're using the spatial data structures that I'm not understanding.  

(3) What are the circumstances under which you'd want the SpatialRTree to be inactive?

**Comment by tomnelson** [comment]
Thank you for providing focused questions. I realize that there is much in
the PR discussion area that is easily overlooked and difficult to find.

(0) Let's start without considering visualization (or anything in
jung-visualization).
 LayoutModel - The LayoutModel holds a mutable mapping of Node to (x,y)
location in (normally 2 dimensional) Euclidean space. It also holds a
reference to the Graph, which serves as a mapping of node relationships in
'graph-space', for example 'what nodes are adjacent to n?' is not
implemented to do an O(N) check of all nodes, instead the Graph
implementation stores those relationships. The Graph is a spatial data
structure optimization in 'graph-space'. Our LayoutModel implementations
are Mediators between graph-space (the Graph) and Euclidean space (the
Map<N,Point>). The LayoutModel does not keep a reference to a
LayoutAlgorithm, but instead accepts a LayoutAlgorithm as a temporary
Visitor. Because the Layout process cares only about point locations for
Nodes, the LayoutModel uses a Graph<N> instead of a Network<N,E>.

 LayoutAlgorithm - The LayoutAlgorithm in the simplest cases considers each
Node from graph-space and places it at a location in Euclidean space. For
the LayoutAlgorithms that are Iterative, they consider each Node from
graph-space, see where is is now in Euclidean space, then using some
heuristic, place the Node at a (new) location in Euclidean space. The
LayoutAlgorithms Visit the LayoutModel in order to perform their operations.

... on the the visualization side

VisualizationModel contains the structure of what is being rendered on the
View side (VisualizationServer and VisualizationViewer). The
VisualizationModel has a reference to a Network<N,E> so that the View side
can get Nodes and Edges to draw them. The VisualizationModel has a
reference to a LayoutModel so that the View side knows where to draw Nodes
and Edges. When the VisualizationModel creates (or gets) a LayoutModel, it
gives the LayoutModel a Graph by calling the Network::asGraph() method. The
Graph in the LayoutModel is a live view of the Network: Mutations of the
Network affect the Graph view.

For our viewing pleasure, the Iterative LayoutAlgorithms can be operated in
a prerelax phase followed by a relax phase. The difference is that the
prerelax phase is operated on the current thread and finishes quickly,
while the relax phase is operated with a new Thread. When the prerelax
phase is started, the LayoutModel is set to not fire events. When the relax
phase is started, the LayoutModel events are re-enabled. The LayoutModel
events are so that the View can know update the rendering of the Network.
That is why our jung-samples can show a Network being updated by its
LayoutAlgorithm in real time. The prerelax phase is used to get the Layout
'close' and the relax phase continues the LayoutAlgorithm work, possibly to
completion. Firing events makes the relax phase steps slower than the
prerelax phase.

(1) I would implement this as a Filter on the View side that, when given a
Node location that is not optimal (by overlapping) it applies a heuristic
to change the location. There would be tricky edge cases to consider for
this, for example, what if there is a large Node shape that does not leave
room for the others? Since the LayoutModel knows only about discreet point
locations for Nodes, I suppose the 'overlap' condition would be when more
than one Node is placed at the identical location. Our ISOMLayoutAlgorithm
will do that frequently. Others do it rarely.

(2) Short answer: There is no difference because the LayoutAlgorithms do
not use the spatial data structures.
     Longer answer: At this time, there is no LayoutAlgorithm in JUNG that
uses a spatial data structure for Nodes in Euclidean space. Let's list the
questions that are optimized by the Euclidean space spatial data structure:
  - return the closest Element to this (x,y) location
  - return all elements that are 'inside' this region (a Shape, usually a
Rectangle or an Ellipse)
       - for picking, a shape is created in the Layout Euclidean space, all
the contained Nodes are fetched, and then each of this small subset of
Graph Nodes is checked to see if the point is contained in the Node shape.
The non-spatial way is to simply check all Nodes for point containment.
       - used for multi-selection with the mouse and also for limiting
rendering to elements that are inside the current zoomed-in view of the
Network)

  Only one JUNG LayoutAlgorithm asks one of those questions offered by a
Spatial model. ISOMLayoutAlgorithm looks for Nodes that are 'close' to
randomly chosen points. The force directed layout algorithms (KK, FR,
Spring) typically consider each node and assign an attraction and repulsion
force for every other node. KKLayoutAlgorithm uses a shortest path
algorithm on the Graph structure (points in 'graph-space'). The
LayoutAlgorithms start with locations that are either randomized in
Euclidean space, or are all at the origin. Since they make decisions based
on every other node, I have not noticed a good application of Euclidean
space spatial data structures for LayoutAlgorithms. Perhaps, once the
LayoutAlgorithm has reached a reasonable state, a Spatial model could limit
force computations to only nodes that are close in Euclidean space, but
since there is a cost to building the spatial structure over and over as
the Graph elements are moved around, this would have to be weighed against
the optimization offered on a LayoutAlgorithm that is nearly complete.

(3) Simple answer: The spatial data structures are inactiive when the
LayoutModel is 'active' (moving things around).
     Longer answer: At this time, the SpatialRTree is inactive when the
LayoutAlgorithm is in its prerelax and relax phase. I may also make it
inactive during certain mouse interactions (like dragging a node) until the
Node has reached its final position (mouse button released).
Here are the steps (in VisualizationServer)

New or changed LayoutAlgorithm:
 1. The VisualizationModel's LayoutModel accepts a new LayoutAlgorithm
 2.  Spatial structures are made inactive
 3. The VisualizationModel determines if the LayoutAlgorithm is iterative
or not
    - if it is Iterative, it runs a quick prerelax, then sets up a Thread
to do the 'relax', when the relax completes, the spatial data structures
are made active.
    - If it is not iterative, the spatial data structures are made active

New or changed Network:
 1. The VisualizationModel gets a new Network: VisualizationModel::
setNetwork(Network)
 2.  the SpatialData structures are cleared
 3.  the LayoutModel is given the Graph for the Network
 4.  the LayoutModel is made to accept the existing LayoutAlgorithm (step 1
above)
     (then follow the same steps above)

**Comment by tomnelson** [comment]
any surprises?

**Comment by jrtom** [comment]
Briefly, layouts like FRLayout have two forces: the attractive force (the edge wants to be a particular length, which mostly translates to attraction in practice) and the repulsive force (nodes don't want to be near other nodes).

For nodes that are connected by an edge, you do need to include the edge-related force regardless of where the endpoints are.  And for those forces the spatial data structure isn't helpful.  

This is one reason why I was toying with the idea of actually splitting layouts like FRLayout into two different pieces (which is effectively how they work now): the edge-attracting piece and the node-repelling piece (which could make use of the spatial data structure).
