### ISSUE TITLE
3d LayoutAlgorithms and Models

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#175]
I recently removed the 3d layout algorithms that I previously created, because I wanted to finish up the spatial layout work without the distraction of having those too. Since I have gotten back to looking at my 3d code, I created the new classes I needed (a 3d Point, plus a Box and a Sphere) and also extended my BarnesHutQuadTree into a BarnedHutOctTree. I integrated the BHOT into the 3d spring layout and the 3d FR Layout. The code is all quite similar to the 2d layout code, adding depth and a z dimension. 

None of the above drags in any new dependencies. 

Are you interested in a PR to add a layout3d package in jung-algorithms that would contain classes to support 3d layout?

**Comment by jrtom** [comment]
I think it's an interesting idea in theory, but I don't recall anyone ever actually asking for 3D graph visualization.  So I appreciate the offer, but at least for the moment, I think I will decline.  (And if anyone _does_ ask in future, I'll let them know that you at least once had a prototype that they might want to check out.)

Thanks!
