### ISSUE TITLE
groupId

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#176]
Years ago, when we first started using Maven, I set the groupId to 'net.sf.jung' (because we were on sourceforge.net).
Do you plan to change the groupId for version 3?

**Comment by jbduncan** [comment]
I can't speak for @jrtom, but that would make sense to me.

How about `com.github.jrtom.jung`?

**Comment by jbduncan** [comment]
Or `com.github.jrtom.jung3`?

**Comment by jrtom** [comment]
I don't see any particular reason to change it, honestly.  If I understand correctly, it just needs to be a consistent unique string (subject to certain [guidelines](https://maven.apache.org/guides/mini/guide-naming-conventions.html).

I did consider this question when I was getting things set up on GitHub (with @cgruber's help) for the 2.1 release, but we didn't come up with any reasons to change it then.

I certainly wouldn't want to put the version number in the string, in any event.

Is there some reason that either of you sees why it might be to our advantage to change it?  Does anyone actually pay attention to this string?

(I thought about trying to acquire the domain jung.net a long time ago, but I don't think that it would have been worth the trouble, and I don't think it likely is now, either.)

**Comment by jbduncan** [comment]
> Is there some reason that either of you sees why it might be to our advantage to change it?

For consistency with the platform/website on which we're doing development on now, really. Having said that, though, it's not a very good reason. Re-thinking things, I think that self-consistency, i.e. keeping the same group ID, would probably make more sense now, as it would produce busywork for us which AFAICT doesn't actually give us anything.

> Does anyone actually pay attention to this string?

I'm sure some people do, but I personally hardly ever do so. It was actually the first time I consciously realised that our group ID was `net.sf.jung` and it's the first time I've realised that `net.sf` comes from SourceForge. So I suppose I've proven my point that it doesn't really give us anything to change the group ID at this stage. :)
