### ISSUE TITLE
JUNG-3 snapshots

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#181]
Will you soon (or are you already) deploying JUNG-3 snaphot jars? Doing so would make it a lot easier for anyone (like me) working on code that depends on some parts of JUNG-3

**Comment by tomnelson** [comment]
I added a change to PR #180 that updates the jdk version in the tools/deploy_snapshots.sh script

Perhaps that will cause the snapshots to deploy again. There are no deployed jung snapshot jars newer than version 2.2, at least none that i could find.

**Comment by jrtom** [comment]
It's been a while since @cgruber helped me set that up, but IIRC we intentionally weren't deploying snapshot jars.  But I agree that even if that were intentional, the JDK version in deploy_snapshots.sh is wrong (wrong JDK).

**Comment by jrtom** [comment]
Resolved with #183.

**Comment by jrtom** [comment]
(Or at least the version issue is resolved.  If you don't start seeing snapshot jars, then please reopen this.)
