### ISSUE TITLE
graph algorithms

### ISSUE THREAD

**Issue by tomnelson** [jrtom/jung#190]
Do you plan to introduce any graph (not layout!) algorithms like shortest path, MST, etc. into common.graph? I ask because I think we may agree that it would be sad if java.util.Collections (or guava) offered no way to sort a list without the use of another library. The precedent for 'algorithms' in a collections package seems to be there.

**Comment by jrtom** [comment]
Yes.  There are a few such algorithms that we haven't released externally yet, but we're working on it.

The question of exactly where the responsibilities for common.graph end and those for a library like JUNG begin is an ongoing long-form debate.  :)
