### ISSUE TITLE
Jung 2.1.1 classes in JAR seem to use old definitions

### ISSUE THREAD

**Issue by aamanlamba** [jrtom/jung#201]
After importing the 2.1.1 jars, I get the error:

```
The constructor VisualizationViewer(Network, LayoutAlgorithm, Dimension) is undefined
```
for the line:

```
VisualizationViewer vv = new 
            VisualizationViewer(g, layoutAlgorithm, new Dimension(900, 900));
```
where

` Network g = NetworkBuilder.undirected().build(); // and other load steps
`
It appears the classes in the Jung 2.1.1 JAR still use the old definitions, for example

`VisualizationViewer(Layout<V,E>,Dimension)
`
and not

`VisualizationViewer(Network<N,E>,Dimension,Dimension)`

I'm using the default jars - this also occurs if I use the 2.1.1 Maven dependency

**Comment by jrtom** [comment]
Nothing in 2.1.1 is using the Guava common.graph types yet; you're seeing something from the as-yet-unreleased-and-unready version 3.0.  I suspect that you may have cloned the current version of JUNG from GitHub rather than using the 2.1.1 release.
