### ISSUE TITLE
Add an edge without specifying its id

### ISSUE THREAD

**Issue by cakcora** [jrtom/jung#205]
This has been major nuisance for me. I wish we could just write graph.addEdge(node1,node2); 

I have to either store an edge count or if using multiple graphs do this

graph.addEdge(graph.getEdgeCount(),node1,node2);

**Comment by jrtom** [comment]
@cakcora The version of JUNG currently in development (3.0-SNAPSHOT) has replaced the JUNG 2.x data model with the [Guava common.graph API](https://github.com/google/guava/wiki/GraphsExplained), which does support graphs with anonymous edges.

If you just want to build a graph and don't need the JUNG algorithms, you can use common.graph directly.  I don't recommend that you depend on JUNG 3.0-SNAPSHOT--it's not stable yet--but you can take a look at its current state if you're interested.
