### ISSUE TITLE
Any plans for RadialTreeLayout?

### ISSUE THREAD

**Issue by florecista** [jrtom/jung#209]
Hi all,

Years ago JUNG had a RadialTreeLayout. There doesn't seem to be one now. Has anyone implemented or plans to implement a RadialTreeLayout? Or is it a case of, "Please feel free to implement one."

Keen on a project, but it requires a Radial Layout.

**Comment by jrtom** [comment]
The latest release (JUNG 2.1.1) still has `RadialTreeLayout`: https://github.com/jrtom/jung/blob/jung-2.1.1/jung-algorithms/src/main/java/edu/uci/ics/jung/algorithms/layout/RadialTreeLayout.java

The 3.0-SNAPSHOT release (i.e., what's currently in the master branch) has refactored the layout algorithms, but there is still a radial layout algorithm: https://github.com/jrtom/jung/blob/f11345d70982c0aa6c60629f6470e960b615dfff/jung-algorithms/src/main/java/edu/uci/ics/jung/layout/algorithms/RadialTreeLayoutAlgorithm.java
that is still demonstrated in some of our sample code (e.g., `TreeLayoutDemo`).
