### ISSUE TITLE
Remove bogus Maven POMs

### ISSUE THREAD

**Issue by jrtom** [jrtom/jung#21]
these include:
* jung/jung-graph-impl/src/main/java/pom.xml 
* jung/jung-visualization/src/main/java/pom.xml 
* jung/jung-io/src/main/java/pom.xml 
* jung/jung-samples/src/main/java/pom.xml 

These look like accidental copies of the top-level pom.xml files located in the top-level subproject directories (jung/subproject/pom.xml).  They probably don't hurt anything but AFAIK they're unnecessary and somewhat confusing.

**Comment by cgruber** [comment]
Fixed in #20
