### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by Nordin-010** [jrtom/jung#232]
Hi guys, I’m new to JUNG and I have difficulties trying out an example. I downloaded all the JAR files of version 2.1.1 and added to my test project using Eclipse. When I try to copy a sample project that needs layout classes, i.e.  edu.uci.ics.jung.layout.* I found out that these classes are not available in one of those JAR files, so my test app can’t build. Are those missing classes obsolete or are they by accident not added? 

I don’t use Maven, as I’m not familiar with Maven, that’s why I chose to use JAR files.
Thank you.

**Comment by jrtom** [comment]
Sorry, somehow this escaped my notice before.

Questions like this are best put on StackOverflow with the tag "jung" (and, in this case, also "java" and "eclipse"), so I'll close this issue and you can take it up there if you haven't already sorted this out.

The most likely scenarios that come to mind are (a) you got the wrong JAR files, or not all of them, or (b) an Eclipse project misconfiguration.
