### ISSUE TITLE
Hypergraph visualization

### ISSUE THREAD

**Issue by epideveloper** [jrtom/jung#248]
Is it possible to create visualizations of hypergraphs using the JUNG library? If so, are there any examples or documentation on how to get started?

**Comment by thomasleaute** [comment]
Have a look at this previous question of mine: https://github.com/jrtom/jung/issues/221

**Comment by epideveloper** [comment]
Thanks for the reference #221. To briefly summarize, there is no current support nor is there any work planned to add functionality to visualize hypergraphs.
