### ISSUE TITLE
weight path

### ISSUE THREAD

**Issue by demirmehmet0** [jrtom/jung#251]
how to get EdmondsKarpMaxFlow step path?

**Comment by jrtom** [comment]
Please ask questions like this on stackoverflow.com: https://stackoverflow.com/questions/ask?tags=jung+java

While your question is unclear--I don't know what you mean by "step path" in this context--I suspect that it may be the same as this question: https://stackoverflow.com/questions/61871639/how-to-get-flow-for-every-edge-using-jungs-edmonds-karp/61882461#61882461
