### ISSUE TITLE
Error calling layout.setSize

### ISSUE THREAD

**Issue by pekadad** [jrtom/jung#255]
This is not a bug (as far as I can tell) but when I call setSize on an instance of a CircleLayout, I am getting this error:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/util/concurrent/internal/InternalFutureFailureAccess

At the point this is thrown, I have created the instance of CircleLayout with the graph I have and then call setSize.

I think this is a versioning issue somewhere but I can't find any reference to this at all through some internet searching.

I am using JUNG 2.1.1, guava 30.0 and JRE 1.8.

**Comment by jrtom** [comment]
This is unrelated to JUNG.  See https://stackoverflow.com/questions/34413/why-am-i-getting-a-noclassdeffounderror-in-java for more information.
