### ISSUE TITLE
Incorrect link to CLA

### ISSUE THREAD

**Issue by wehddn** [jrtom/jung#266]
The file [CONTRIBUTING.md](https://github.com/jrtom/jung/blob/master/CONTRIBUTING.md) contains a link to the CLA, which seems to be incorrect : `There is no CLA to sign for jrtom/jung`

**Comment by jrtom** [comment]
I believe it should be fixed now; apparently it was a permissions issue (had to reauthorize the tool).

Please reopen if you're still seeing this behavior.
