### ISSUE TITLE
Suggestion: manage annotations in AnnotationPaintable as a list instead of a set

### ISSUE THREAD

**Issue by cbrinkrolf** [jrtom/jung#271]
First of all: thank you for this library, I am using it for more than a decade already!

I suggest to change the variable storing the collection of annotations in [AnnotationPaintable](https://github.com/jrtom/jung/blob/master/jung-visualization/src/main/java/edu/uci/ics/jung/visualization/annotations/AnnotationPaintable.java) from the currently used Set to List to ensure a predictable order in which the annotations are painted by AnnotationPaintable.paint(). Esp. for overlapping annotations, the order of painting is crucial such that a second annotations covers (partially) the previously added annotation. Currently, this is not ensured,e.g., a second annotations is painted first and is (partially) hidden by a previously added annotation.

For my project, I changed the variable from HashSet to ArrayList and so far, annotations are handled and painted as expected. What do you think about the suggestion. Is it a meaningful improvement or did i overlook something?

**Comment by jrtom** [comment]
@cbrinkrolf thanks, we're glad you've found it useful!  :)

I think it's reasonable to guarantee an iteration order for the annotations, but I think a better solution for that is to use a  `LinkedHashSet` in place of `HashSet` for the annotations; that way you keep the Set semantics (especially "no duplicates") and still get the predictable iteration order.  I'll look into that.

**Comment by jrtom** [comment]
Done in #272 .

**Comment by cbrinkrolf** [comment]
I can confirm, it works as expected, thank you for this quick fix :)
