### ISSUE TITLE
Patch for /trunk/jung/jung-io/src/main/java/edu/uci/ics/jung/io/MatrixFile.java

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jrtom/jung#3]
```
Decimal separators are different in different countries, e.g. comma instead of 
a dot.
String.format uses default locale whereas load() method uses 
Double.parseDouble() which can't cope with commas.
```

Original issue reported on code.google.com by `marcin.czekaj` on 6 Nov 2011 at 6:41

Attachments:
* [MatrixFile.java.patch](https://storage.googleapis.com/google-code-attachments/jung/issue-3/comment-0/MatrixFile.java.patch)

**Comment by jrtom** [comment]
MatrixFile is no longer part of JUNG 2.1; closing this as obsolete.
