### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by digitalw** [jrtom/jung#34]
Hi,
Is there any kind of documentation available?

thanks.

**Comment by jrtom** [comment]
http://jrtom.github.io/jung/ has a link to the current Javadoc.

http://jung.sourceforge.net/doc/index.html has references to several older documents and tutorials.
I will be making updated versions of some of these available on the GitHub site as time allows.

The distribution also includes sample code, which you may find useful.

**Comment by digitalw** [comment]
Thanks allot, the first link to the current javadoc is what i needed.
