### ISSUE TITLE
BasicVisualizationServer causes NullPointerException

### ISSUE THREAD

**Issue by dominic-jones** [jrtom/jung#44]
Running even simple visualisations such as https://gist.github.com/dominic-jones/5fdb31055838aefe07e2 will cause a NullPointerException in 2.1

Traced back to a refactoring done here acf6eac7d09d93cb2d775223c4b8da22babe0c51.

In short, the PluggableRenderContext was previously (in 2.0.1) initalised at field declaration. Now in 2.1 intialisation has been relocated to the constructors.

Since several of these constructors call a main one, any data set into PluggableRenderContext by the primary constructor is overridden.

Ultimately, the NPE occurs later at BasicVertexLabelRenderer#84 where the pickedVertexState in PluggableRenderContext has been nulled.

Happy to contribute back a test and a fix for this if that would be easier for you.

**Comment by dominic-jones** [comment]
A sample, if basic, fix has been submitted here.
https://github.com/jrtom/jung/pull/45

Really though, this is only the minimum possible fix and you might wish to opt for a different approach. Happy to take feedback and expand it however!

**Comment by jrtom** [comment]
The above-referenced commits provide a good-enough fix for this issue.  Thanks!
