### ISSUE TITLE
how do i use JUNG

### ISSUE THREAD

**Issue by Safouane** [jrtom/jung#5]
Is there a GUI to start testing algorithms?

**Comment by jrtom** [comment]
I'm not sure what you're looking for, but JUNG is a library, not a tool, so while you can use it to build a GUI, it doesn't have one of its own.

JUNG certainly has visualization capabilities; take a look at the visualization package and the sample code.

**Comment by Safouane** [comment]
Yes, that was my question, And your answer is sufficient. Thank you.
