### ISSUE TITLE
Lattice2DGenerator getRow() bug

### ISSUE THREAD

**Issue by JMMarchant** [jrtom/jung#53]
The calculation for getRow() is currently incorrect. Consider the following scenario. The numbers represent vertices and are arranged in a 2-row, 5-col lattice.

    0 1 2 3 4
    5 6 7 8 9

getRow() currently returns `i / row_count` which means that vertices 2-3 are incorrectly said to be in row 1, 4-5 in row 2 (non-existent), 6-7 in row 3 (non-existent), etc.

Changing it to `i / col_count` produces the desired results: 0-4 are row 0, 5-9 are row 1.

This code doesn't seem to be used anywhere except in the Kleinberg generator but within that it is used to calculate the distance metric between nodes for making the long-distance connections. This means that the probabilities assigned to the nodes is incorrect as the nodes are thought to be potentially much further away than they are.

It also means that it is possible for the vertices to have self-loops/duplicate attempted edges as the check to prevent this relies on the distance between the nodes.

**Comment by jrtom** [comment]
Well-spotted.  Thanks for the fix!
(If you feel like adding to the unit tests for this, we'd welcome that as well.  :) )
