### ISSUE TITLE
NullPointerException “AWT-EventQueue-0” labelVertex(BasicVertexLabelRenderer.java:84)

### ISSUE THREAD

**Issue by Claus1** [jrtom/jung#60]
Minimal example. I use Scala so excuse me)

import java.awt.Dimension
import javax.swing.JFrame

import edu.uci.ics.jung.graph.util.EdgeType
import edu.uci.ics.jung.algorithms.layout.StaticLayout
import edu.uci.ics.jung.graph._
import edu.uci.ics.jung.visualization.{BasicVisualizationServer, GraphZoomScrollPane, VisualizationViewer}

object GrViz {

  private var svg = new SparseMultigraph[String,String]

  def add(t: String, str: String, str1: String): Unit =
  {
      svg.addEdge(t, str,str1, EdgeType.DIRECTED)
  }

  def show_model {
    add("t","a","b")
    show
  }

  def show{
    var layout = new StaticLayout(svg);
    layout.setSize(new Dimension(800, 600));
    
    var vv = new BasicVisualizationServer[String,String](layout);
    vv.setPreferredSize(new Dimension(350,350)); //Sets the viewing area size

    var frame = new JFrame("View");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.getContentPane().add(vv);
    frame.pack();
    frame.setVisible(true);
  }
}

**Comment by Claus1** [comment]
If switch to 2.0.1 there is no exception but empty screen with 1/4 red point in left upper corner instead 2 vertex graph.

**Comment by jrtom** [comment]
I believe that this is likely the same issue as #44, fixed in #45.  If getting the latest code does not fix this issue, please reopen.
