### ISSUE TITLE
Xlint:path error with JUNG, Gradle and Error Prone

### ISSUE THREAD

**Issue by jbduncan** [jrtom/jung#66]
When I try to run `gradle run` with the following `build.gradle`

``` gradle
plugins {
  id 'application'
  id 'java'
  id 'net.ltgt.errorprone' version '0.0.8'
}

group 'org.jbduncan'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

mainClassName = 'org.jbduncan.helloworld.HelloWorld'

repositories {
  jcenter()
}

dependencies {
  compile 'net.sf.jung:jung-graph-impl:2.1.1'
  errorprone 'com.google.errorprone:error_prone_core:2.0.11'
}

tasks.withType(JavaCompile) {
  options.encoding = 'UTF-8'
  options.compilerArgs = [
    '-Xlint:all',
    '-Werror'
  ]
}
```

and this class

``` java
package org.jbduncan.helloworld;

public final class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello, world!");
  }
}
```

it emits the following message.

```
:compileJava                                                                     
warning: [path] bad path element "C:\Users\Jonathan\.gradle\caches\modules-2\files-2.1\net.sf.jung\jung-graph-impl\2.1.1\8293acb2ab4c00a3939cb99a8751e5d38a4299dc\jung-api-2.1.1.jar": no such file or directory
warning: [path] bad path element "C:\Users\Jonathan\.gradle\caches\modules-2\files-2.1\net.sf.jung\jung-graph-impl\2.1.1\8293acb2ab4c00a3939cb99a8751e5d38a4299dc\guava-19.0.jar": no such file or directory
warning: [path] bad path element "C:\Users\Jonathan\.gradle\caches\modules-2\files-2.1\net.sf.jung\jung-api\2.1.1\e47ee4efdfacce12f0af620747d9d0e44bf2eaa4\guava-19.0.jar": no such file or directory
error: warnings found and -Werror specified
1 error                     
3 warnings
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.488 secs
```

When I investigate the contents of my Gradle cache, I can see that, indeed, the jar files mentioned above simply don't exist.

When I look into `C:\Users\Jonathan\.gradle\caches\modules-2\files-2.1\net.sf.jung\jung-graph-impl\2.1.1\8293acb2ab4c00a3939cb99a8751e5d38a4299dc\jung-graph-impl-2.1.1.jar`, the `META-INF/MANIFEST.MF` contains this text.

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.0.5
Built-By: jrtom
Build-Jdk: 1.8.0-google-v7
Class-Path: jung-api-2.1.1.jar guava-19.0.jar
```

I get the same problem with JUNG versions 2.1 and 2.0, and no other library with dependencies I've tried seems to have this problem. 

However the problem goes away when I exclude from `build.gradle` the lines `id 'net.ltgt.errorprone' version '0.0.8'` and `errorprone 'com.google.errorprone:error_prone_core:2.0.11'`, so it's not clear to me if this is a problem with JUNG or if it's [gradle-errorprone-plugin](https://github.com/tbroyer/gradle-errorprone-plugin) or Error Prone related.

**Comment by jrtom** [comment]
You've got me.  No one's reported such an error to me before, and I've never used Gradle.  If you change the version of errorprone does it make a difference?  Have you reported this to errorprone (or on StackOverflow) to see if they've seen something like this?

**Comment by jbduncan** [comment]
Thanks for getting back @jrtom. I just upgraded from Error Prone 2.0.11 to 2.0.13, but that doesn't seem to be fixed the problem.

I'll report this on Error Prone and let you know if I manage to move things forward.

**Comment by jbduncan** [comment]
Hmm, no-one seems to be replying on Error Prone (https://github.com/google/error-prone/issues/466). I'll see if I can find an answer on StackOverflow.

**Comment by jbduncan** [comment]
http://stackoverflow.com/questions/40050098/how-do-i-fix-this-xlintpath-error-when-using-gradle-jung-and-error-prone

**Comment by jbduncan** [comment]
I've also posted this issue on the [Gradle forums](https://discuss.gradle.org/t/unable-to-use-xlint-all-in-a-gradle-project-with-gradle-errorprone-plugin-and-jung-library/20038).

**Comment by jbduncan** [comment]
Hi @jrtom, it looks like it's both a subtle bug in JSR 199 and a misconfiguration in the way the JUNG jar is packaged. See https://github.com/google/error-prone/issues/466#issuecomment-255808445 for more details.

**Comment by jrtom** [comment]
@jbduncan I'm kind of swamped at the moment (with work and with other JUNG stuff), but if you'd like to try making that change and submitting a pull request if it works, I'd be happy to review it.  Otherwise I'll try to get to it when I can.

**Comment by jbduncan** [comment]
Hi @jrtom, I've just had time to tackle this issue, and so I've submitted a PR (https://github.com/jrtom/jung/pull/75) which causes the following Gradle build file (based on the example I gave [here](https://github.com/jrtom/jung/issues/66#issue-181006682)) to work without any build problems (using `./gradlew build`, specifically).

```gradle
plugins {
  id 'application'
  id 'java'
  id 'net.ltgt.errorprone' version '0.0.8'
}

ext {
  versions = [
    errorprone: '2.0.11',
    jung: '2.2-SNAPSHOT'
  ]
}

group 'org.jbduncan'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

mainClassName = 'org.jbduncan.helloworld.HelloWorld'

repositories {
  mavenLocal()
  // jcenter()
}

dependencies {
  compile "net.sf.jung:jung-graph-impl:${versions.jung}"
  errorprone "com.google.errorprone:error_prone_core:${versions.errorprone}"
}

configurations.errorprone {
  resolutionStrategy.force "com.google.errorprone:error_prone_core:${versions.errorprone}"
}

tasks.withType(JavaCompile) {
  options.encoding = 'UTF-8'
  options.compilerArgs = [
    '-Xlint:all',
    '-Werror'
  ]
}
```

**Comment by jrtom** [comment]
@jbduncan  I've accepted your change in #75.  Thanks!  :)
