### ISSUE TITLE
Fix up the maven poms so that deployment to sonatype is a one-liner

### ISSUE THREAD

**Issue by cgruber** [jrtom/jung#7]
This should include:

  - [x] Update the deployment information to point to sonatype
  - [x] Add a profile keyed on a flag like -DperformRelease=true
  - [x] Move Jung to declare -SNAPSHOT versions at-head, reserving non-snapshot versions for release
  - [x] File issues on issues.sonatype.org for Josh and any other developers who need to perform releases
  - [x] throw a script in to ease release, or use maven-release-plugin and configure accordingly.

Optional:

  - [x] Set up travis-ci.org configuration to run continuous integration on successful merges to master
  - [x] Set up the .travis.yml to auto-deploy snapshot releases to sonatype on successful merge to master.

**Comment by cgruber** [comment]
#15 and #16 create the basic Travis configuration.  Travis builds are now on all pull requests and all non-gh-pages branches pushed on the main repo.

**Comment by cgruber** [comment]
Snapshot versions listed in #12

**Comment by cgruber** [comment]
Sonatype is registered for cgruber and jrtom to push binaries to the repos.

**Comment by cgruber** [comment]
#19 adds a release profile "sonatype-oss-release" which can be activated via -Psonatype-oss-release

**Comment by jrtom** [comment]
So where are we on sonatype at this point?  That is, I see the issue you filed on sonatype (https://issues.sonatype.org/browse/OSSRH-20435) but I don't understand what our next steps are there.  Is it just a matter of actually cutting and performing a release at this point?

**Comment by cgruber** [comment]
yes.  It's all on our side. I'll add a release script and instructions, and then we can go ahead... though I would seriously consider upgrading to a modern guava first.

**Comment by jrtom** [comment]
Already upgraded to Guava 19.0 in #30.  :)

**Comment by jrtom** [comment]
Not quite a one-liner, but the instructions in [RELEASE.md](https://github.com/jrtom/jung/blob/master/RELEASE.md) work now.  :)
