### ISSUE TITLE
Consider changing EdgeShape inner classes to nested static classes

### ISSUE THREAD

**Issue by jrtom** [jrtom/jung#70]
In the refactoring of EdgeShape.java (moving from 2.0 to 2.1), we changed the Line, QuadCurve, etc. classes from nested static classes into inner classes.  While in general the refactoring was a distinct improvement, the static->inner change is one we should consider undoing.

Credit where due: this was originally brought up by @timboudreau in #69.

**Comment by tomnelson** [comment]
I saw the comment and was wondering if I had done that (made them inner classes). I see that it was done later on. I am also curious about why.

**Comment by jrtom** [comment]
@tomnelson the "we" that changed it was in fact me.  :)  I don't specifically remember why I did that, except that it was in the context of other cleanup of that class and might have been only quasi-intentional.

**Comment by timboudreau** [comment]
Performance-wise, you're better off with a static nested class.  While it seems trivial, inner classes add an extra level of indirection to dereference fields in their parent instance - and this is code that can be called thousands of times for one call to `paint()` - if that causes CPU cache misses, those can add up.

**Comment by tomnelson** [comment]
This is complete.

**Comment by jrtom** [comment]
Thanks, @tomnelson.
