### ISSUE TITLE
PluggableRendercontext does not properly reset EdgeShape

### ISSUE THREAD

**Issue by pdvrieze** [jrtom/jung#73]
When setting a new graph on a model/layout/visualizer it would be expected that this works correctly. Unfortunately EdgeShape keeps a reference to the original graph and attempts to use that to determine whether there is a loop (and fails). A workaround is to manually reset the edgeshapetransform on the pluggablerendercontext after setting the graph.

The Kotlin code below shows the problem (and the workaround), I'd like to get rid of the last two code lines.

```
var graph: Graph<MyVertex, MyEdge> = graph
   set(value)
   {
      field = value
      graphViewer.graphLayout = FRLayout(graph)
      // Hack as edgeshape is broken in that it keeps a reference to the previous graph
      graphViewer.renderContext.edgeShapeTransformer = EdgeShape.quadCurve(graph)
    }
```

**Comment by jrtom** [comment]
This was fixed a while back; please reopen if you still see this problem.
