### ISSUE TITLE
DelegateTree's removeVertex method doesn't properly handle removal of the root

### ISSUE THREAD

**Issue by ddenton** [jrtom/jung#76]
I have a use case where I would like to empty an existing DelegateTree and add a new root vertex.  However, the `removeVertex()` method does not set the `root` field to null when called to remove the root vertex.  Because `addVertex()` will throw an exception if the `root` field is not null, this means that `addVertex()` can never be used to set a new root even after the original root has been removed.  The fix is very simply to add

    if (root != null && root.equals(vertex)) {
        root = null;
    }

to `removeVertex()`.

I can understand a school of thought that says that we don't handle empty trees, and that replacing the root should involve the creation of a new tree.  (This would be inconvenient for my use case, but it would be an understandable position.) However, this isn't consistent with the the rest of DelegateTree. First, DelegateTree has constructors that allow the creation of empty trees.  Second, and more damning, `removeVertex()` is currently fine with removing the root vertex from the delegate and removing the stored depth of the root vertex.  This leaves the DelegateTree in a corrupted state where `getRoot()` will still return a reference to the removed vertex, even though the rest of the object will behave as if it is no longer present in the tree.

**Comment by jrtom** [comment]
Lots of things, including the layout algorithms, are being refactored at the moment in preparation for the release of JUNG 3.0.  We'll make sure this gets addressed.  Thanks for the heads-up.

**Comment by jrtom** [comment]
This is fixed in 3.0-SNAPSHOT (i.e., what's currently checked into the master branch).
