### ISSUE TITLE
Multiple viewers for multiple graphs within a common frame.

### ISSUE THREAD

**Issue by DavePosner** [jrtom/jung#98]
This is probably easy but currently the viewer displays in the content container of a JFrame.  I would like to have multiple vv's displaying in separate panels of a single JFrame I tried replacing the JFrame with a JPanel but got nothing.  I do not have a deep understanding of awt so I'm probably missing something but would it be possible to enable this feature?

**Comment by jrtom** [comment]
Several of the sample applications (in the jung-samples package) demonstrate this capability.  `MultiViewDemo`, for instance.
